// SPDX-License-Identifier: GPL-3.0-or-later
// Offline corpus generated by the pinned production server packetizer, not a
// second implementation of the wire format. No capture, network or GPU calls.
#include "src/crypto.h"
#include "src/pyrowave_transport.h"
extern "C" {
#include "src/rswrapper.h"
}
#include <algorithm>
#include <array>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <iterator>
#include <stdexcept>

namespace protocol = pyrowave::protocol;
namespace transport = pyrowave::transport;
using bytes_t = std::vector<std::uint8_t>;

static void write_u32(std::ostream &out, std::uint32_t value) {
    for (unsigned shift = 0; shift != 32; shift += 8) out.put(static_cast<char>(value >> shift));
}

static bytes_t read_file(const std::filesystem::path &path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) throw std::runtime_error("Cannot read fixture input");
    return {std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>()};
}

static void generate(const std::filesystem::path &directory, const char *name,
                     const bytes_t &frame, bool encrypted, std::uint32_t fec_percentage = 20
#ifdef PYROWAVE_FIXTURE_V2
                     , bool fragmented = false
#endif
                     ) {
    protocol::transport_config_t config;
    config.packet_size = 1024;
    config.path_mtu = 1280;
    config.ip_header_size = 40;
    config.fec_percentage = fec_percentage;
    config.min_fec_packets = 2;
    config.encrypted = encrypted;
#ifdef PYROWAVE_FIXTURE_V2
    config.fragmented = fragmented;
    config.critical_fec_percentage = fec_percentage ? std::max(40u, fec_percentage) : 0;
    const auto plan = fragmented ? protocol::plan_fragmented_transport(frame, config) : protocol::plan_transport(frame.size(), config);
#else
    const auto plan = protocol::plan_transport(frame.size(), config);
#endif
    const auto packetized = transport::packetize_frame(frame, config, 123);
    if (!plan || !packetized) throw std::runtime_error("Production frame budget rejected fixture");
    const auto basename = std::string(name) + (encrypted ? "-encrypted.pwrt" : "-clear.pwrt");
    std::ofstream out(directory / basename, std::ios::binary);
    if (!out) throw std::runtime_error("Cannot create transport fixture");
    std::uint32_t count = 0;
    for (std::uint32_t i = 0; i < plan->block_count; ++i)
        count += plan->blocks[i].data_shards + plan->blocks[i].parity_shards;
    out.write("PWRT", 4);
    write_u32(out, 1);
    write_u32(out, config.packet_size);
    write_u32(out, encrypted ? 1 : 0);
    write_u32(out, count);

    crypto::cipher::gcm_t cipher({0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}, false);
    std::uint64_t counter = 0;
    std::uint32_t sequence = 0;
    std::size_t offset = 0;
    for (std::uint32_t block = 0; block < plan->block_count; ++block) {
        const auto length = std::min<std::size_t>(
            plan->blocks[block].data_shards * (config.packet_size + 16), packetized->size() - offset);
        const auto encoded = transport::encode_block(
            std::span(*packetized).subspan(offset, length), plan->blocks[block], config,
            {1, sequence, 0x10203040, block, plan->block_count}, encrypted ? &cipher : nullptr, counter);
        if (!encoded) throw std::runtime_error("Production block encoder rejected fixture");
        for (std::size_t i = 0; i < encoded->size(); ++i) {
            const auto prefix = encoded->prefix(i);
            const auto shard = encoded->shard(i);
            write_u32(out, static_cast<std::uint32_t>(prefix.size() + shard.size()));
            if (!prefix.empty()) out.write(reinterpret_cast<const char *>(prefix.data()), prefix.size());
            out.write(reinterpret_cast<const char *>(shard.data()), shard.size());
        }
        sequence += static_cast<std::uint32_t>(encoded->size());
        offset += length;
    }
    if (!out) throw std::runtime_error("Transport fixture write failed");
    std::cout << basename << ": " << plan->block_count << " blocks, " << count << " datagrams\n";
}

int main(int argc, char **argv) {
    try {
        if (argc != 3) throw std::runtime_error("Usage: generate INPUT_720P_PWVF OUTPUT_DIRECTORY");
        const std::filesystem::path directory(argv[2]);
        std::filesystem::create_directories(directory);
        reed_solomon_init();
        const auto encoded = read_file(argv[1]);
        const auto parsed = protocol::parse_frame(encoded);
        if (!parsed) throw std::runtime_error("Invalid source PWVF fixture");
        const auto image = protocol::serialize_frame(1, 123456789, parsed->packets, protocol::max_frame_size);
        bytes_t native(800000);
        for (std::size_t i = 0; i < native.size(); ++i) native[i] = static_cast<std::uint8_t>(i * 31 + i / 256);
        const std::array<std::span<const std::uint8_t>, 1> packets{native};
        const auto large = protocol::serialize_frame(1, 123456789, packets, protocol::max_frame_size);
        if (!image || !large) throw std::runtime_error("Fixture serialization failed");
        for (const auto &[name, frame] : std::array<std::pair<const char *, const bytes_t *>, 2>{
                {{"720p", &*image}, {"four-block", &*large}}}) {
            std::ofstream expected(directory / (std::string(name) + ".pwvf"), std::ios::binary);
            expected.write(reinterpret_cast<const char *>(frame->data()), frame->size());
            if (!expected) throw std::runtime_error("Expected frame write failed");
            generate(directory, name, *frame, false);
            generate(directory, name, *frame, true);
        }
        for (const auto fec : {0u, 1u, 100u, 255u}) {
            const auto name = "720p-fec" + std::to_string(fec);
            generate(directory, name.c_str(), *image, false, fec);
            generate(directory, name.c_str(), *image, true, fec);
        }
        return 0;
    } catch (const std::exception &error) {
        std::cerr << error.what() << '\n';
        return 1;
    }
}
